//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Images
    {
        public int Img_Id { get; set; }
        public string Img1 { get; set; }
        public Nullable<int> Pro_Id { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }
        public string Img4 { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
    }
}
