//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact
    {
        public int Con_ID { get; set; }
        public string User_Email { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public int User_ID { get; set; }
        public string Name { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
    }
}
